name: Build Safari Extension Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      example_dir:
        description: 'Example directory to build'
        required: false
        default: 'example'
        type: string

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.example_dir || 'example' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ${{ github.event.inputs.example_dir || 'example' }}/package.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Convert extension
        run: npm run convert
      
      - name: Build unsigned IPA
        run: npm run build:ios
      
      - name: Build macOS app
        run: npm run build:macos
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: safari-extension
          path: |
            ${{ github.event.inputs.example_dir || 'example' }}/safari-extension/ios-app/dist/*.ipa
            ${{ github.event.inputs.example_dir || 'example' }}/safari-extension/macos-app/dist/*.app.zip
          retention-days: 7