name: Release Safari Extension Example

on:
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: ''
      example_dir:
        description: 'Example directory to release'
        required: false
        default: 'example'
        type: string

jobs:
  release:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.example_dir || 'example' }}
    env:
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
      APPLE_API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
      APPLE_API_KEY_CONTENT: ${{ secrets.APPLE_API_KEY_CONTENT }}
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package.json'
      
      - name: Install root dependencies
        working-directory: ${{ github.workspace }}
        run: npm install
        
      - name: Install example dependencies
        run: npm install
      
      - name: Set version
        if: github.event.inputs.version != ''
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          sed -i '' 's/"version": "[^"]*"/"version": "${{ github.event.inputs.version }}"/' safari-extension.config.js
      
      - name: Convert extension
        run: npm run convert
      
      - name: Build and sign for TestFlight
        if: env.APPLE_TEAM_ID != ''
        run: npm run build:testflight
      
      - name: Build macOS app
        run: npm run build:macos
      
      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.event.inputs.example_dir || 'example' }}/safari-extension/ios-app/dist/
            ${{ github.event.inputs.example_dir || 'example' }}/safari-extension/macos-app/dist/